apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"redux-saga-nginx"},"name":"redux-saga-kubernetes","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redux-saga-kubernetes"}},"template":{"metadata":{"labels":{"app":"redux-saga-kubernetes"}},"spec":{"containers":[{"image":"gcr.io/kubernetes-test-290013/redux-saga-kuberenetes@sha256:59682a24b812fa2b00b5d3cae10a2799d5ef3027c14375589b8aa4d8c84c980f","imagePullPolicy":"Always","name":"redux-saga-kubernetes","ports":[{"containerPort":80}]}],"restartPolicy":"Always"}}}}
  creationTimestamp: "2020-09-29T17:06:23Z"
  generation: 17
  labels:
    app: redux-saga-nginx
  name: redux-saga-kubernetes
  namespace: default
  resourceVersion: "1877955"
  selfLink: /apis/apps/v1/namespaces/default/deployments/redux-saga-kubernetes
  uid: 1cb8d013-4247-4e6d-a975-5e07cb3878e8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redux-saga-kubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redux-saga-kubernetes
    spec:
      containers:
      - image: gcr.io/kubernetes-test-290013/redux-saga-kuberenetes@sha256:212c5242b7fa7c4d54e9c5c7785c3ed24cb0373a87c736fae897e28d8db99b88
        imagePullPolicy: Always
        name: redux-saga-kubernetes
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-29T18:37:55Z"
    lastUpdateTime: "2020-09-29T18:37:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-29T18:20:50Z"
    lastUpdateTime: "2020-10-05T15:46:18Z"
    message: ReplicaSet "redux-saga-kubernetes-65c6d6ffc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 17
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redux-saga-kubernetes","namespace":"default"},"spec":{"ports":[{"nodePort":31000,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"redux-saga-nginx"},"type":"NodePort"}}
  creationTimestamp: "2020-09-29T17:06:24Z"
  name: redux-saga-kubernetes
  namespace: default
  resourceVersion: "12273"
  selfLink: /api/v1/namespaces/default/services/redux-saga-kubernetes
  uid: e9a6fc1a-c557-440e-9efb-9ed488faf0d5
spec:
  clusterIP: 10.4.8.197
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: redux-saga-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-09-29T17:08:00Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: redux-saga-nginx
  name: redux-saga-kubernetes-service
  namespace: default
  resourceVersion: "12780"
  selfLink: /api/v1/namespaces/default/services/redux-saga-kubernetes-service
  uid: 796dca29-9674-410f-85be-1f94f6a7d382
spec:
  clusterIP: 10.4.0.255
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31219
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: redux-saga-kubernetes
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.123.81.247
