kind: Deployment
apiVersion: apps/v1
metadata:
  name: redux-saga-kubernetes
  labels:
    app: redux-saga-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redux-saga-kubernetes
  template:
    metadata:
      labels:
        app: redux-saga-kubernetes
    spec:
      containers:
        - name: redux-saga-kubernetes
          image: gcr.io/kubernetes-test-290013/redux-saga-kuberenetes@sha256:be8f7faa04dceb64d590be1f4b2775a461e5dcdc14a914be0e8a994034dd6773
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: redux-saga-kubernetes
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: redux-saga-kubernetes